server {
    listen 80;
    server_name localhost;
    client_max_body_size 500M;
    # 公共端入口
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 管理端入口
    location /admin {
        alias /usr/share/nginx/html/admin;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    # API 代理
    location /api {
        proxy_pass http://backend:8000;
	client_max_body_size 500M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # 登录 Auth
    location /token {
        proxy_pass http://backend:8000;
    }

    # 静态文件下载 (直接由 Nginx 提供，高效)
    location /files {
        alias /usr/share/nginx/html/files;
        autoindex off;
    }
}
