server {
    listen 80;
    client_max_body_size 500M;

    # 公共下载端
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 管理后台
    location /admin {
        alias /usr/share/nginx/html/admin;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    # API 转发
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /token {
        proxy_pass http://backend:8000;
    }

    location /files {
        alias /usr/share/nginx/html/files;
    }
}
